ambariserver:
    image: incloud/ambari-hawq:patch
    ports:
        - "8080:8080"
    privileged: true
    net: none
    volumes:
        - /mnt/hgfs/hadoop-w/docker:/share
        #持久化数据目录
        - /data/psql/:/var/lib/pgsql/data/
        #- /data/jia1/keys/:/var/lib/ambari-server/keys/
        - ./etc-hosts:/etc/hosts
    command: ["/start-server.sh","setup"]
    dns_search: docker
    hostname: ambariserver
    environment:
       #- "constraint:role==master"
       - "constraint:nodename==jia1"
hmaster: #run on jia1
    image: incloud/ambari-hawq:patch
    privileged: true
    net: none
    volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
        - /root/.docker/machine/machines/jia1:/jia1-cert
        - /mnt/hgfs/hadoop-w/docker:/share
        #持久化数据目录
        - /data/hmaster/hdfs/:/hadoop/hdfs/
        - /data/hmaster/hawq/:/data/hawq/
        - /data/hmaster/zookeeper/:/hadoop/zookeeper/
        - ./etc-hosts:/etc/hosts
    command: ["/start-agent.sh","reset","ambariserver"]
    dns_search: docker
    hostname: hmaster
    environment:
       #- "constraint:role==master"
       - "constraint:nodename==jia1"
       - HADOOP_ROLE=master
       - DOCKER_CERT_PATH=/jia1-cert
       - DOCKER_TLS_VERIFY=1
       - DOCKER_URI=tcp://192.168.200.11:3376
    labels:
       hadoop.role: "slave"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
hsecond: #run on jia1
    extends:
       service: hmaster
    hostname: hsecond
    environment:
       - "constraint:nodename==jia1"
       - HADOOP_ROLE=slave
    volumes:
        #持久化数据目录
        - /data/hsecond/hdfs/:/hadoop/hdfs/
        - /data/hsecond/hawq/:/data/hawq/
hwork1: # run on jia1
    extends:
       service: hmaster
    hostname: hwork1
    environment:
       - "constraint:nodename==jia1"
       - HADOOP_ROLE=slave
    volumes:
        #持久化数据目录
        - /data/hwork1/hdfs/:/hadoop/hdfs/
        - /data/hwork1/hawq/:/data/hawq/
hwork2: # run on jia2
    extends:
       service: hmaster
    hostname: hwork2
    environment:
       - "constraint:nodename==jia2"
       - HADOOP_ROLE=slave
    volumes:
        #持久化数据目录
        - /data/hwork2/hdfs/:/hadoop/hdfs/
        - /data/hwork2/hawq/:/data/hawq/
hwork3: # run on jia3
    extends:
       service: hmaster
    hostname: hwork3
    environment:
       - "constraint:nodename==jia3"
       - HADOOP_ROLE=slave
    volumes:
        #持久化数据目录
        - /data/hwork3/hdfs/:/hadoop/hdfs/
        - /data/hwork3/hawq/:/data/hawq/